# Generated by Django 5.1.15 on 2026-04-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('production_per_day', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('order_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для заказа')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('critical_minimum', models.FloatField(default=0)),
                ('delivery_days', models.IntegerField(default=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('is_consumable', models.BooleanField(default=False)),
                ('consumable_per_device', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_received', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.part')),
            ],
        ),
        migrations.CreateModel(
            name='DevicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_device', models.FloatField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.device')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.part')),
            ],
        ),
    ]
