services:
  - type: web
    name: msklad
    env: python
   buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
   releaseCommand: python manage.py migrate
   startCommand: gunicorn your_project.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DISABLE_POETRY
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
